title: Laura Le # your name (or website title) here
logo: "/images/loan.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A data analyst with data management, statistics, machine learning know-how and marketing experience looking for opportunities to help companies make data driven business decisions.  
  <br><br>
 
  <a href="https://www.linkedin.com/in/laurale68/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
